DROP TABLE IF EXISTS `department`;
DROP TABLE IF EXISTS `employee`;
CREATE TABLE `department` (
  `ID` int(2) DEFAULT NULL,
  `NAME` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE employee (
  `ID` int(4) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) DEFAULT NULL,
  `SALARY` float DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `DEPT_NO` int(2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;
